target_sources(wb_atoms PRIVATE
  webassembly/src/atoms/legacy/atoms_template_facade.cpp
  webassembly/src/atoms/application/density_service_legacy_port_adapter.cpp
  webassembly/src/atoms/application/measurement_controller.cpp
  webassembly/src/atoms/application/measurement_service_legacy_port_adapter.cpp
  webassembly/src/atoms/application/structure_service_legacy_port_adapter.cpp
  webassembly/src/atoms/application/structure_lifecycle_service.cpp
  webassembly/src/atoms/application/structure_read_model.cpp
  webassembly/src/atoms/application/visibility_service.cpp
  webassembly/src/atoms/domain/atom_manager.cpp
  webassembly/src/atoms/domain/bond_manager.cpp
  webassembly/src/atoms/domain/bz_plot.cpp
  webassembly/src/atoms/domain/cell_manager.cpp
  webassembly/src/atoms/domain/cell_transform.cpp
  webassembly/src/atoms/domain/charge_density.cpp
  webassembly/src/atoms/domain/crystal_structure.cpp
  webassembly/src/atoms/domain/crystal_system.cpp
  webassembly/src/atoms/domain/element_database.cpp
  webassembly/src/atoms/domain/measurement_geometry.cpp
  webassembly/src/atoms/domain/structure_state_store.cpp
  webassembly/src/atoms/domain/surrounding_atom_manager.cpp
  webassembly/src/atoms/infrastructure/batch_update_system.cpp
  webassembly/src/atoms/infrastructure/bond_renderer.cpp
  webassembly/src/atoms/infrastructure/bz_plot_layer.cpp
  webassembly/src/atoms/infrastructure/charge_density_renderer.cpp
  webassembly/src/atoms/infrastructure/vtk_renderer.cpp
  webassembly/src/atoms/presentation/builder_windows_controller.cpp
  webassembly/src/atoms/presentation/editor_windows_controller.cpp
  webassembly/src/atoms/presentation/isosurface_panel.cpp
  webassembly/src/atoms/presentation/slice_view_panel.cpp
  webassembly/src/atoms/ui/atom_editor_ui.cpp
  webassembly/src/atoms/ui/bond_ui.cpp
  webassembly/src/atoms/ui/bravais_lattice_ui.cpp
  webassembly/src/atoms/ui/bz_plot_ui.cpp
  webassembly/src/atoms/ui/cell_info_ui.cpp
  webassembly/src/atoms/ui/charge_density_ui.cpp
  webassembly/src/atoms/ui/periodic_table_ui.cpp
  webassembly/src/structure/domain/structure_repository.cpp
  webassembly/src/structure/application/structure_service.cpp
  webassembly/src/measurement/application/measurement_service.cpp
  webassembly/src/density/application/density_service.cpp
)
