#!/usr/bin/env python3
"""Validate atom/grid axis alignment for XSF files.

This script ranks the 6 axis permutations (`xyz`, `xzy`, `yxz`, `yzx`, `zxy`, `zyx`)
by sampling DATAGRID values at atom positions after axis correction.

Optionally, when molecule info is available from TABS.pdf, it also reports a geometry
RMSD score against reference atom coordinates.
"""

from __future__ import annotations

import argparse
import itertools
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np


AXES: Tuple[str, ...] = tuple("".join(p) for p in itertools.permutations("xyz"))
TOKEN_BEGIN_GRID = "BEGIN_DATAGRID_3D"
TOKEN_END_GRID = "END_DATAGRID_3D"


@dataclass
class GridBlock:
    label: str
    dims: Tuple[int, int, int]
    origin: np.ndarray  # shape (3,)
    vectors: np.ndarray  # shape (3, 3), rows are X/Y/Z vectors
    values: np.ndarray  # shape (nx, ny, nz), i-fastest source order
    mean: float
    std: float


@dataclass
class AxisScore:
    axis: str
    grid_score: float
    grid_score_z: float
    best_grid_label: str
    geom_rmsd: Optional[float]
    geom_shift: Optional[np.ndarray]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Rank axis permutations by atom/grid alignment score and infer likely --axis value."
        )
    )
    parser.add_argument(
        "--xsf",
        type=Path,
        required=True,
        help="Path to XSF file generated by extract_tabs_info.py (must include DATAGRID_3D)",
    )
    parser.add_argument(
        "--grid-label",
        type=str,
        default=None,
        help=(
            "Only use this DATAGRID label (e.g. feature:ch_0). "
            "Default: evaluate all grids and use the best score per axis."
        ),
    )
    parser.add_argument(
        "--molecule-number",
        type=int,
        default=None,
        help=(
            "Molecule number for geometry RMSD validation against TABS.pdf "
            "(optional but recommended)."
        ),
    )
    parser.add_argument(
        "--pdf-path",
        type=Path,
        default=Path("xsf_examples/TABS.pdf"),
        help="Path to TABS.pdf for geometry RMSD validation (default: xsf_examples/TABS.pdf)",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=6,
        help="How many ranked axis candidates to print (default: 6)",
    )
    return parser.parse_args()


def _is_keyword_line(stripped: str) -> bool:
    if not stripped:
        return False
    token = stripped.split()[0]
    if token in {
        "CRYSTAL",
        "SLAB",
        "POLYMER",
        "MOLECULE",
        "ATOMS",
        "PRIMVEC",
        "CONVVEC",
        "PRIMCOORD",
        "BEGIN_BLOCK_DATAGRID_3D",
        "END_BLOCK_DATAGRID_3D",
        "BEGIN_BLOCK_BANDGRID_3D",
        "END_BLOCK_BANDGRID_3D",
    }:
        return True
    return token.startswith("BEGIN_") or token.startswith("END_")


def _label_from_begin_datagrid(line: str) -> str:
    stripped = line.strip()
    label = stripped[len(TOKEN_BEGIN_GRID) :].strip()
    if label and label[0] in "_:-":
        label = label[1:]
    return label if label else "grid"


def parse_xsf_atoms(lines: Sequence[str]) -> Tuple[np.ndarray, np.ndarray]:
    atoms_z: List[int] = []
    atoms_xyz: List[Tuple[float, float, float]] = []

    # 1) ATOMS section (preferred for DATAGRID files)
    for i, line in enumerate(lines):
        if line.strip().startswith("ATOMS"):
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                if not stripped:
                    j += 1
                    continue
                if _is_keyword_line(stripped):
                    break
                parts = stripped.split()
                if len(parts) >= 4:
                    try:
                        z = int(float(parts[0]))
                        x = float(parts[1])
                        y = float(parts[2])
                        zc = float(parts[3])
                        atoms_z.append(z)
                        atoms_xyz.append((x, y, zc))
                    except ValueError:
                        pass
                j += 1
            if atoms_xyz:
                return np.array(atoms_z, dtype=int), np.array(atoms_xyz, dtype=float)

    # 2) PRIMCOORD section fallback
    for i, line in enumerate(lines):
        if line.strip().startswith("PRIMCOORD"):
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j >= len(lines):
                break
            header = lines[j].split()
            if not header:
                break
            try:
                natoms = int(float(header[0]))
            except ValueError:
                break
            j += 1
            for _ in range(natoms):
                if j >= len(lines):
                    break
                parts = lines[j].split()
                if len(parts) >= 4:
                    try:
                        z = int(float(parts[0]))
                        x = float(parts[1])
                        y = float(parts[2])
                        zc = float(parts[3])
                        atoms_z.append(z)
                        atoms_xyz.append((x, y, zc))
                    except ValueError:
                        pass
                j += 1
            if atoms_xyz:
                return np.array(atoms_z, dtype=int), np.array(atoms_xyz, dtype=float)

    raise ValueError("Failed to parse atom coordinates from XSF (ATOMS/PRIMCOORD not found).")


def parse_datagrids(lines: Sequence[str], grid_label_filter: Optional[str]) -> List[GridBlock]:
    blocks: List[GridBlock] = []
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if not stripped.startswith(TOKEN_BEGIN_GRID):
            i += 1
            continue

        label = _label_from_begin_datagrid(lines[i])
        i += 1
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i >= len(lines):
            break

        dims_line = np.fromstring(lines[i], sep=" ")
        if dims_line.size < 3:
            raise ValueError(f"Invalid DATAGRID dims for '{label}'")
        dims = (int(dims_line[0]), int(dims_line[1]), int(dims_line[2]))
        i += 1

        origin_line = np.fromstring(lines[i], sep=" ")
        if origin_line.size < 3:
            raise ValueError(f"Invalid DATAGRID origin for '{label}'")
        origin = origin_line[:3].astype(float)
        i += 1

        vectors = np.zeros((3, 3), dtype=float)
        for row in range(3):
            vec_line = np.fromstring(lines[i], sep=" ")
            if vec_line.size < 3:
                raise ValueError(f"Invalid DATAGRID vectors for '{label}'")
            vectors[row, :] = vec_line[:3]
            i += 1

        selected = grid_label_filter is None or label == grid_label_filter
        values_chunks: List[np.ndarray] = []
        while i < len(lines):
            s = lines[i].strip()
            if s.startswith(TOKEN_END_GRID):
                i += 1
                break
            if selected:
                arr = np.fromstring(lines[i], sep=" ")
                if arr.size:
                    values_chunks.append(arr.astype(float))
            i += 1

        if not selected:
            continue

        expected = dims[0] * dims[1] * dims[2]
        if not values_chunks:
            raise ValueError(f"No DATAGRID values found for '{label}'")
        values_1d = np.concatenate(values_chunks, axis=0)
        if values_1d.size < expected:
            raise ValueError(
                f"DATAGRID '{label}' has too few values ({values_1d.size} < {expected})"
            )
        if values_1d.size > expected:
            values_1d = values_1d[:expected]

        values = values_1d.reshape(dims, order="F")
        mean = float(np.mean(values))
        std = float(np.std(values))
        blocks.append(
            GridBlock(
                label=label,
                dims=dims,
                origin=origin,
                vectors=vectors,
                values=values,
                mean=mean,
                std=std,
            )
        )

    if not blocks:
        if grid_label_filter:
            raise ValueError(f"DATAGRID label '{grid_label_filter}' not found")
        raise ValueError("No DATAGRID_3D blocks found in XSF")
    return blocks


def axis_apply(coords: np.ndarray, axis: str) -> np.ndarray:
    idx = [("x", "y", "z").index(ch) for ch in axis]
    return coords[:, idx]


def axis_inverse_apply(coords: np.ndarray, axis: str) -> np.ndarray:
    # axis string means: out = (in[axis[0]], in[axis[1]], in[axis[2]])
    # inverse: in_x = out[pos('x')] ...
    inv = [axis.index("x"), axis.index("y"), axis.index("z")]
    return coords[:, inv]


def world_to_index(points: np.ndarray, grid: GridBlock) -> np.ndarray:
    m = np.column_stack([grid.vectors[0], grid.vectors[1], grid.vectors[2]])
    try:
        inv_m = np.linalg.inv(m)
    except np.linalg.LinAlgError as exc:
        raise ValueError(f"Grid '{grid.label}' has singular vectors matrix") from exc

    frac = (points - grid.origin.reshape(1, 3)) @ inv_m.T
    dims_minus_1 = np.array([grid.dims[0] - 1, grid.dims[1] - 1, grid.dims[2] - 1], dtype=float)
    return frac * dims_minus_1.reshape(1, 3)


def trilinear_sample(arr: np.ndarray, indices: np.ndarray) -> np.ndarray:
    nx, ny, nz = arr.shape
    out = np.full((indices.shape[0],), np.nan, dtype=float)

    for p, (ix, iy, iz) in enumerate(indices):
        if not (0.0 <= ix <= nx - 1 and 0.0 <= iy <= ny - 1 and 0.0 <= iz <= nz - 1):
            continue

        i0 = int(math.floor(ix))
        j0 = int(math.floor(iy))
        k0 = int(math.floor(iz))
        i1 = min(i0 + 1, nx - 1)
        j1 = min(j0 + 1, ny - 1)
        k1 = min(k0 + 1, nz - 1)
        dx = ix - i0
        dy = iy - j0
        dz = iz - k0

        c000 = arr[i0, j0, k0]
        c100 = arr[i1, j0, k0]
        c010 = arr[i0, j1, k0]
        c110 = arr[i1, j1, k0]
        c001 = arr[i0, j0, k1]
        c101 = arr[i1, j0, k1]
        c011 = arr[i0, j1, k1]
        c111 = arr[i1, j1, k1]

        c00 = c000 * (1 - dx) + c100 * dx
        c10 = c010 * (1 - dx) + c110 * dx
        c01 = c001 * (1 - dx) + c101 * dx
        c11 = c011 * (1 - dx) + c111 * dx
        c0 = c00 * (1 - dy) + c10 * dy
        c1 = c01 * (1 - dy) + c11 * dy
        out[p] = c0 * (1 - dz) + c1 * dz

    return out


def grid_axis_scores(xsf_atoms: np.ndarray, grids: Sequence[GridBlock]) -> Dict[str, Tuple[float, float, str]]:
    result: Dict[str, Tuple[float, float, str]] = {}
    for axis in AXES:
        corrected = axis_inverse_apply(xsf_atoms, axis)

        best_raw = -float("inf")
        best_z = -float("inf")
        best_label = ""

        for grid in grids:
            idx = world_to_index(corrected, grid)
            sampled = trilinear_sample(grid.values, idx)
            valid = sampled[np.isfinite(sampled)]
            if valid.size == 0:
                raw = -float("inf")
                zscore = -float("inf")
            else:
                raw = float(np.mean(valid))
                zscore = float((raw - grid.mean) / (grid.std + 1.0e-12))

            if zscore > best_z:
                best_z = zscore
                best_raw = raw
                best_label = grid.label

        result[axis] = (best_raw, best_z, best_label)
    return result


def load_reference_atoms(
    molecule_number: int, pdf_path: Path
) -> Tuple[np.ndarray, np.ndarray]:
    from extract_tabs_info import find_molecule_lines, parse_molecule_data, symbol_to_atomic_number

    lines = find_molecule_lines(pdf_path, molecule_number)
    mol = parse_molecule_data(molecule_number, lines)
    z = np.array([symbol_to_atomic_number(sym) for sym, _, _, _ in mol.atoms], dtype=int)
    xyz = np.array([(x, y, zc) for _, x, y, zc in mol.atoms], dtype=float)
    return z, xyz


def geometry_axis_scores(
    xsf_z: np.ndarray,
    xsf_xyz: np.ndarray,
    ref_z: np.ndarray,
    ref_xyz: np.ndarray,
) -> Dict[str, Tuple[float, np.ndarray]]:
    if xsf_xyz.shape != ref_xyz.shape:
        raise ValueError(
            f"Atom count mismatch between XSF ({xsf_xyz.shape[0]}) and reference ({ref_xyz.shape[0]})"
        )
    if xsf_z.shape != ref_z.shape:
        raise ValueError("Atomic number array shape mismatch")

    if np.any(xsf_z != ref_z):
        mismatch = int(np.sum(xsf_z != ref_z))
        raise ValueError(
            f"Atomic number/order mismatch in {mismatch} atoms; "
            "cannot compute reliable geometry RMSD."
        )

    scores: Dict[str, Tuple[float, np.ndarray]] = {}
    for axis in AXES:
        pred = axis_apply(ref_xyz, axis)
        shift = np.mean(xsf_xyz - pred, axis=0)
        diff = xsf_xyz - (pred + shift.reshape(1, 3))
        rmsd = float(np.sqrt(np.mean(np.sum(diff * diff, axis=1))))
        scores[axis] = (rmsd, shift)
    return scores


def print_ranked_scores(scores: Sequence[AxisScore], top_k: int) -> None:
    print("Axis ranking (best first):")
    print("axis  grid_zscore  grid_mean       best_grid_label     geom_rmsd")
    print("----  -----------  -------------   ------------------  ----------")
    for row in scores[:top_k]:
        geom = f"{row.geom_rmsd:.6e}" if row.geom_rmsd is not None else "N/A"
        print(
            f"{row.axis:>4}  {row.grid_score_z:>11.6f}  {row.grid_score:>13.6e}   "
            f"{row.best_grid_label:<18}  {geom}"
        )


def main() -> int:
    args = parse_args()

    if not args.xsf.exists():
        print(f"Error: XSF file not found: {args.xsf}", file=sys.stderr)
        return 2

    lines = args.xsf.read_text(encoding="utf-8", errors="ignore").splitlines()
    xsf_z, xsf_xyz = parse_xsf_atoms(lines)
    grids = parse_datagrids(lines, args.grid_label)

    grid_scores = grid_axis_scores(xsf_xyz, grids)

    geom_scores: Optional[Dict[str, Tuple[float, np.ndarray]]] = None
    if args.molecule_number is not None:
        if not args.pdf_path.exists():
            print(f"Error: PDF file not found: {args.pdf_path}", file=sys.stderr)
            return 2
        try:
            ref_z, ref_xyz = load_reference_atoms(args.molecule_number, args.pdf_path)
            geom_scores = geometry_axis_scores(xsf_z, xsf_xyz, ref_z, ref_xyz)
        except Exception as exc:
            print(f"Warning: geometry RMSD validation skipped: {exc}", file=sys.stderr)
            geom_scores = None

    merged: List[AxisScore] = []
    for axis in AXES:
        raw, zscore, label = grid_scores[axis]
        if geom_scores is not None:
            rmsd, shift = geom_scores[axis]
        else:
            rmsd, shift = None, None
        merged.append(
            AxisScore(
                axis=axis,
                grid_score=raw,
                grid_score_z=zscore,
                best_grid_label=label,
                geom_rmsd=rmsd,
                geom_shift=shift,
            )
        )

    if geom_scores is not None:
        merged.sort(key=lambda x: (x.geom_rmsd if x.geom_rmsd is not None else float("inf"), -x.grid_score_z))
    else:
        merged.sort(key=lambda x: -x.grid_score_z)

    print(f"Input XSF: {args.xsf}")
    print(f"Parsed atoms: {xsf_xyz.shape[0]}")
    print(f"Parsed DATAGRIDs: {len(grids)}")
    if args.grid_label:
        print(f"Grid filter: {args.grid_label}")
    print_ranked_scores(merged, top_k=max(1, min(args.top_k, 6)))

    best = merged[0]
    print("")
    print(f"Recommended --axis value: {best.axis}")
    print(
        "Interpretation: this axis gives the best atom-grid alignment score "
        f"(and geometry RMSD when available)."
    )
    if best.geom_shift is not None:
        print(
            f"Best geometry translation shift: "
            f"({best.geom_shift[0]:.6f}, {best.geom_shift[1]:.6f}, {best.geom_shift[2]:.6f})"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
